version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images...
      - docker build -t m4lf3s/custom-balena-base-arm:sdl2    
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - docker push m4lf3s/custom-balena-base-arm:sdl2

